version: '3.8'

services:
  web:
    image: "django:latest"
    build:
      target: development_build
      context: .
      cache_from:
        - "django:latest"
    command: bash -c "python src/manage.py migrate && python src/manage.py auto_create_superuser && python src/manage.py runserver 0.0.0.0:8000"
    ports:
      - 8000:8000
    env_file:
      - env
    depends_on:
      - db

  db:
    container_name: my-sqlite-container
    image: alpine:latest
    volumes:
      - sqlite-data:/mydatabase
    ports:
      - "5432:5432"
    env_file:
      - env

volumes:
  sqlite-data:
