version: '3.8'

services:
  web:
    image: "django-demo:dev"
    build:
      target: development_build
      context: .
      cache_from:
        - "django-demo:dev"
        - "django-demo:latest"
        - "*"
      args:
        DJANGO_ENV: development
    command: python -Wd manage.py runserver 0.0.0.0:8000
    ports:
      - 8000:8000
    env_file:
      - ./env.example
    depends_on:
      - db

  db:
    container_name: my-sqlite-container
    image: sqlite:latest
    volumes:
      - sqlite-data:/mydatabase
    ports:
      - "5432:5432"
    env_file:
      - ./.env.dev

volumes:
  sqlite-data:
