# Generated by Django 5.0 on 2023-12-05 19:06

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("vendor", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PurchaseOrder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "po_number",
                    models.CharField(help_text="Purchase order number.", max_length=10),
                ),
                (
                    "order_date",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        help_text="Date when the purchase order was created.",
                    ),
                ),
                (
                    "delivery_date",
                    models.DateTimeField(help_text="Expected delivery date."),
                ),
                (
                    "items",
                    models.JSONField(
                        default=dict, help_text="JSON representation of ordered items."
                    ),
                ),
                (
                    "quantity",
                    models.PositiveIntegerField(
                        default=0, help_text="Total quantity of items in the order."
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "pending"),
                            ("completed", "completed"),
                            ("canceled", "canceled"),
                        ],
                        help_text="Status of the purchase order.",
                        max_length=100,
                    ),
                ),
                (
                    "quality_rating",
                    models.FloatField(
                        blank=True,
                        help_text="Quality rating for the purchase.",
                        null=True,
                    ),
                ),
                (
                    "issue_date",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Date when the purchase order was issued.",
                    ),
                ),
                (
                    "acknowledgment_date",
                    models.DateTimeField(
                        blank=True,
                        help_text="Date when the purchase order was acknowledged.",
                        null=True,
                    ),
                ),
                (
                    "vendor",
                    models.ForeignKey(
                        help_text="Vendor associated with the purchase order.",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="vendor.vendor",
                    ),
                ),
            ],
        ),
    ]
