# Generated by Django 5.0 on 2023-12-05 19:08

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("order", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="purchaseorder",
            name="id",
            field=models.UUIDField(
                db_index=True,
                default=uuid.uuid4,
                editable=False,
                help_text="Unique identifier for the purchase_order.",
                primary_key=True,
                serialize=False,
                unique=True,
            ),
        ),
    ]
