# Generated by Django 5.0 on 2023-12-07 10:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("order", "0002_alter_purchaseorder_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="purchaseorder",
            name="po_number",
            field=models.CharField(
                db_index=True,
                help_text="Purchase order number.",
                max_length=10,
                unique=True,
            ),
        ),
    ]
