# Generated by Django 5.0 on 2023-12-05 19:30

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("vendor", "0002_rename_uid_vendor_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="HistoricalPerformance",
            fields=[
                (
                    "on_time_delivery_rate",
                    models.FloatField(
                        default=0, help_text="Percentage of on-time deliveries."
                    ),
                ),
                (
                    "quality_rating_avg",
                    models.FloatField(default=0, help_text="Average quality rating."),
                ),
                (
                    "average_response_time",
                    models.FloatField(
                        default=0, help_text="Average response time in hours."
                    ),
                ),
                (
                    "fulfillment_rate",
                    models.FloatField(
                        default=0, help_text="Percentage of fulfillment rate."
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identifier for the HistoricalPerformance.",
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                (
                    "date",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Date when the historical performance was recorded.",
                    ),
                ),
                (
                    "vendor",
                    models.ForeignKey(
                        help_text="Vendor associated with the historical performance.",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="vendor.vendor",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
