# Generated by Django 5.0 on 2023-12-08 09:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("history", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicalperformance",
            name="date",
            field=models.DateTimeField(
                auto_now_add=True,
                help_text="Date when the historical performance was recorded.",
            ),
        ),
        migrations.AlterField(
            model_name="historicalperformance",
            name="on_time_delivery_rate",
            field=models.FloatField(default=0, help_text="rate of on-time deliveries."),
        ),
    ]
